# Generated by Django 3.1.2 on 2021-11-23 09:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=200, verbose_name='Team')),
                ('logo', models.ImageField(upload_to='teams')),
            ],
        ),
        migrations.CreateModel(
            name='UpcomingMatche',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_tournament', models.DateTimeField(verbose_name='Date of Match')),
                ('team_1', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, related_name='upcomingmatche_requests_created', to='api.teammodel', verbose_name='Team 1')),
                ('team_2', models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.PROTECT, to='api.teammodel', verbose_name='Team 2')),
            ],
        ),
        migrations.CreateModel(
            name='BetModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(50), django.core.validators.MaxValueValidator(1000)], verbose_name='Bet Amount')),
                ('status', models.CharField(blank=True, choices=[('Win', 'Win'), ('Lose', 'Lose'), ('Ongoing', 'Ongoing')], default='', max_length=10, null=True, verbose_name='Bet Status')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Time of Bet')),
                ('better', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Better')),
                ('matches', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.upcomingmatche', verbose_name='Matches')),
                ('pick', models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to='api.teammodel', verbose_name='Picked Team')),
            ],
        ),
    ]
